/**:
    ros__parameters:
        n_aruco_ids: 6
        aruco_size: 0.3 # meters
        gate_size: 2.4 # meters
        camera_model: "pinhole"
        # camera_matrix:
        #     rows: 3
        #     cols: 3
        #     data: [438.783367, 0.000000, 305.593336, 0.000000, 437.302876, 243.738352, 0.000000, 0.000000, 1.000000]
        # distortion_model: "plumb_bob"
        # distortion_coefficients:
        #     rows: 1
        #     cols: 5
        #     data: [-0.361976, 0.110510, 0.001014, 0.000505, 0.000000]
        camera_qos_reliable: false
        
